import { BuildableGeneratorSchema } from './BuildableGenerator';
import { Reference } from './Reference';

describe(`schema.BuildableGenerator`, () => {
  it(`parses Build_GeneratorNuclear_C from v114480`, () => {
    const result = BuildableGeneratorSchema.parse({
      ClassName: "Build_GeneratorNuclear_C",
      mCachedLoadPercentage: "0.000000",
      mWasteLeftFromCurrentFuel: "0",
      mFuelClasses: "",
      mDefaultFuelClasses: "(/Game/FactoryGame/Resource/Parts/NuclearFuelRod/Desc_NuclearFuelRod.Desc_NuclearFuelRod_C)",
      mAvailableFuelClasses: "",
      mFuelResourceForm: "RF_SOLID",
      mRequiresSupplementalResource: "True",
      mSupplementalLoadAmount: "10000",
      mSupplementalToPowerRatio: "2.000000",
      mCachedInputConnections: "",
      mCachedPipeInputConnections: "",
      mPowerProduction: "2500.000000",
      mPowerProductionExponent: "1.321928",
      mLoadPercentage: "0.000000",
      mPowerConsumption: "0.000000",
      mPowerConsumptionExponent: "1.600000",
      mOnHasPowerChanged: "()",
      mOnHasProductionChanged: "()",
      mMinimumProducingTime: "2.000000",
      mMinimumStoppedTime: "5.000000",
      mNumCyclesForProductivity: "20",
      mCanChangePotential: "True",
      mMinPotential: "0.010000",
      mMaxPotential: "1.000000",
      mMaxPotentialIncreasePerCrystal: "0.500000",
      mFluidStackSizeDefault: "SS_FLUID",
      mFluidStackSizeMultiplier: "1",
      OnReplicationDetailActorCreatedEvent: "()",
      mSignificanceBias: "0.500000",
      mEffectUpdateInterval: "2.000000",
      mAddToSignificanceManager: "True",
      mSignificanceRange: "48000.000000",
      mDisplayName: "Nuclear Power Plant",
      mDescription: "Consumes Nuclear Fuel Rods and Water to produce power.\r\nHas a conveyor belt and pipeline input so loading can be automated.  \r\nProduces Nuclear Waste, which is extracted from the conveyor belt output.",
      MaxRenderDistance: "-1.000000",
      mHighlightVector: "(X=0.000000,Y=0.000000,Z=0.000000)",
      mMaterialNameToInstanceManager: "()",
      mSkipBuildEffect: "False",
      mBuildEffectSpeed: "0.000000",
      mForceNetUpdateOnRegisterPlayer: "False",
      mShouldShowHighlight: "False",
      mAllowCleranceSeparationEvenIfStackedOn: "False",
      mInteractingPlayers: "",
      mIsUseable: "True",
    });

    expect(result).toStrictEqual({
      ClassName: "Build_GeneratorNuclear_C",
      mDefaultFuelClasses: [
        new Reference('/Game/FactoryGame/Resource/Parts/NuclearFuelRod/Desc_NuclearFuelRod.Desc_NuclearFuelRod_C'),
      ],
      mFuelResourceForm: "RF_SOLID",
      mRequiresSupplementalResource: true,
      mSupplementalLoadAmount: 10000,
      mSupplementalToPowerRatio: 2.0,
      mPowerProduction: 2500.0,
      mPowerProductionExponent: 1.321928,
      mPowerConsumption: 0.0,
      mPowerConsumptionExponent: 1.6,
      mMinimumProducingTime: 2.0,
      mMinimumStoppedTime: 5.0,
      mNumCyclesForProductivity: 20,
      mCanChangePotential: true,
      mMinPotential: 0.01,
      mMaxPotential: 1.0,
      mMaxPotentialIncreasePerCrystal: 0.5,
      mSignificanceBias: 0.5,
      mEffectUpdateInterval: 2.0,
      mAddToSignificanceManager: true,
      mSignificanceRange: 48000.0,
      mDisplayName: "Nuclear Power Plant",
      mDescription: "Consumes Nuclear Fuel Rods and Water to produce power.\nHas a conveyor belt and pipeline input so loading can be automated.  \nProduces Nuclear Waste, which is extracted from the conveyor belt output.",
      MaxRenderDistance: -1.0,
      mHighlightVector: { X: 0.0, Y: 0.0, Z: 0.0 },
      mSkipBuildEffect: false,
      mBuildEffectSpeed: 0.0,
      mForceNetUpdateOnRegisterPlayer: false,
      mShouldShowHighlight: false,
      mAllowCleranceSeparationEvenIfStackedOn: false,
      mIsUseable: true,
    });
  });
});
