import { Indexable } from './Indexable';
import { ImageId, EntityKind, HumanReadableString, Slug, ItemForm } from './primitive';

/**
 * Any entity which can be built by the player (factory buildings, foundations,
 * conveyers, etc).
 */
export interface Building extends Indexable {
  kind: EntityKind.Building;

  /**
   * A detailed description of the building.
   */
  description: HumanReadableString;

  /**
   * A large image of the building, for display in detail pages.
   */
  poster?: ImageId;

  // Common collections of metadata.

  /**
   * Whether the building can be overclocked.
   */
  overclockable?: true;

  /**
   * The amount of power consumed by this buildable.
   */
  powerConsumption?: BuildingPowerConsumption;

  /**
   * The amount of power generated by this buildable.
   */
  powerProduction?: BuildingPowerProduction;

  // Specific building type details.

  /**
   * Dimensions of the storage provided by a building.
   */
  storage?: BuildingStorageDetails;

  /**
   * Details about the conveyance of the building.
   */
  conveyor?: BuildingConveyorDetails;
}

// Common collections of metadata.

/**
 * Measure of power consumption for a building.
 */
export interface BuildingPowerConsumption {
  amount: number;
  exponent: number;
}

/**
 * Measure of power production for a building.
 */
export interface BuildingPowerProduction {
  amount: number;
  exponent: number;
  fuels?: Slug[];
  fuelForm?: ItemForm;
}

// Specific building type details.

/**
 * Dimensions of a storage container.
 */
export interface BuildingStorageDetails {
  x: number;
  y: number;
}

/**
 * Details about a conveyor.
 */
export interface BuildingConveyorDetails {
  speed: number;
}
