import { Recipe, Item, EntityKind, ItemForm } from '@local/schema';

export const recipes: Recipe[] = [
  {
    name: 'Alternate: Recycled Plastic',
    ingredients: [
      { item: 'rubber', count: 6 },
      { item: 'fuel', count: 6000 },
    ],
    products: [{ item: 'plastic', count: 12 }],
    producedIn: ['refinery'],
    handcraftedIn: [],
    duration: 12,
    manualMultiplier: 1,
    alternate: true,
    slug: 'recipe-alternate-recycled-plastic',
  },
  {
    name: 'Alternate: Recycled Rubber',
    ingredients: [
      { item: 'plastic', count: 6 },
      { item: 'fuel', count: 6000 },
    ],
    products: [{ item: 'rubber', count: 12 }],
    producedIn: ['refinery'],
    handcraftedIn: [],
    duration: 12,
    manualMultiplier: 1,
    alternate: true,
    slug: 'recipe-alternate-recycled-rubber',
  },
  {
    name: 'Iron Ingot',
    ingredients: [{ item: 'iron-ore', count: 1 }],
    products: [{ item: 'iron-ingot', count: 1 }],
    producedIn: ['smelter'],
    handcraftedIn: ['craft-bench'],
    duration: 2,
    manualMultiplier: 3,
    slug: 'recipe-iron-ingot',
  },
  {
    name: 'Iron Plate',
    ingredients: [{ item: 'iron-ingot', count: 3 }],
    products: [{ item: 'iron-plate', count: 2 }],
    producedIn: ['constructor'],
    handcraftedIn: ['craft-bench'],
    duration: 6,
    manualMultiplier: 1,
    slug: 'recipe-iron-plate',
  },
  {
    name: 'Iron Rod',
    ingredients: [{ item: 'iron-ingot', count: 1 }],
    products: [{ item: 'iron-rod', count: 1 }],
    producedIn: ['constructor'],
    handcraftedIn: ['craft-bench'],
    duration: 4,
    manualMultiplier: 0.5,
    slug: 'recipe-iron-rod',
  },
  {
    name: 'Plastic',
    ingredients: [{ item: 'crude-oil', count: 3000 }],
    products: [
      { item: 'plastic', count: 2 },
      { item: 'heavy-oil-residue', count: 1000 },
    ],
    producedIn: ['refinery'],
    handcraftedIn: [],
    duration: 6,
    manualMultiplier: 1,
    slug: 'recipe-plastic',
  },
  {
    name: 'Reinforced Iron Plate',
    ingredients: [
      { item: 'iron-plate', count: 6 },
      { item: 'screw', count: 12 },
    ],
    products: [{ item: 'reinforced-iron-plate', count: 1 }],
    producedIn: ['assembler'],
    handcraftedIn: ['craft-bench'],
    duration: 12,
    manualMultiplier: 1,
    slug: 'recipe-reinforced-iron-plate',
  },
  {
    name: 'Residual Fuel',
    ingredients: [{ item: 'heavy-oil-residue', count: 6000 }],
    products: [{ item: 'fuel', count: 4000 }],
    producedIn: ['refinery'],
    handcraftedIn: [],
    duration: 6,
    manualMultiplier: 1,
    slug: 'recipe-residual-fuel',
  },
  {
    name: 'Rubber',
    ingredients: [{ item: 'crude-oil', count: 3000 }],
    products: [
      { item: 'rubber', count: 2 },
      { item: 'heavy-oil-residue', count: 2000 },
    ],
    producedIn: ['refinery'],
    handcraftedIn: [],
    duration: 6,
    manualMultiplier: 1,
    slug: 'recipe-rubber',
  },
  {
    name: 'Screw',
    ingredients: [{ item: 'iron-rod', count: 1 }],
    products: [{ item: 'screw', count: 4 }],
    producedIn: ['constructor'],
    handcraftedIn: ['craft-bench'],
    duration: 6,
    manualMultiplier: 1,
    slug: 'recipe-screw',
  },
];

export const resources: Item[] = [
  {
    kind: EntityKind.Item,
    name: 'Crude Oil',
    description:
      'Crude Oil is refined into all kinds of Oil-based resources, like Fuel and Plastic.',
    form: ItemForm.Liquid,
    icon: '12ZdJbUI8IUq8Am8s026MI2G9RugCa9aq8qKwYUWqmMa',
    fluid: {
      color: '#19019ff',
    },
    fuel: {
      energy: 0.32,
    },
    raw: true,
    categories: ['Fluids'],
    slug: 'crude-oil',
  },
  {
    kind: EntityKind.Item,
    name: 'Iron Ore',
    description: 'Used for crafting.\nThe most essential basic resource.',
    form: ItemForm.Solid,
    icon: '5c0Gl1FsvuGGyGe28Mg2m87B3HVLJL6oKusESIUocEkS',
    stackSize: 100,
    raw: true,
    categories: ['Resource'],
    slug: 'iron-ore',
  },
];
